In [1]:
import pandas as pd
import numpy as np

In [12]:
df = pd.read_csv(r'C:\Users\Cameron\OneDrive\Documents\DCU_Data\MWBW full dataset 2377 participants_anonymised (1).csv')

df = df.replace(np.nan, None)

np_array = df.to_numpy()

VO2_Data_Prediction = np_array[:,[1,2,3,4,5,6,7,8,9,13,16,34,35,36,37,99,159,160,178,195,213,229,254,265,279,293,310,324,344,360,374,388,402,419,433,444,234,241]]

array_index = range(1,2378)

pandas_array = pd.DataFrame(VO2_Data_Prediction, index = array_index, columns = ['confident_after_school', 'confident_ask_parent', 'confident_regardless_tvcomputer', 
                                                           'confident_regardless_weather', 'confident_home', 'confident_skills', 'confident_busy',
                                                           'confident_best_friend', 'overall_confidence', 'new_calc_bmi', 'WCcm', 'intrinsic_mean', 
                                                           'identified_mean', 'introjected_mean', 'external_mean', 'pa_mean_selfreport', 
                                                           'balance_step_total', 'balance_beam_total', 'puntkick_total', 'handpass_total', 
                                                           'groundstrike_total', 'balance_catch_total', 'run_total', 'skip_total', 'gallop_total',
                                                           'slide_total', 'hop_total', 'hj_total', 'vj_total', 'catch_total', 'throw_total', 'roll_total',
                                                           'kick_total', '2hs_total', '1hs_total', 'bounce_total', 'grip_total', 'plank_total'])

#pandas_array.to_csv(r'C:\Users\Cameron\OneDrive\Documents\DCU_Data\DataSet1.csv')
#pandas_array.info()
pandas_array.describe()

,confident_after_school,confident_ask_parent,confident_regardless_tvcomputer,confident_regardless_weather,confident_home,confident_skills,confident_busy,confident_best_friend,overall_confidence,new_calc_bmi,...,vj_total,catch_total,throw_total,roll_total,kick_total,2hs_total,1hs_total,bounce_total,grip_total,plank_total
count,958.0,958.0,958.0,958.0,958.0,958.0,958.0,958.0,958.00,1958.000000,...,2072.0,2072.0,2078.0,2094.0,2073.0,2076.0,2072.0,2075.0,2026.0,919.00
unique,3.0,3.0,3.0,3.0,3.0,3.0,3.0,3.0,20.00,1759.000000,...,13.0,7.0,9.0,10.0,9.0,11.0,9.0,7.0,366.0,216.00
top,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,1.75,16.259105,...,12.0,6.0,6.0,6.0,8.0,8.0,0.0,6.0,21.8,1.17
freq,800.0,684.0,524.0,640.0,744.0,721.0,590.0,795.0,194.00,5.000000,...,496.0,1142.0,398.0,520.0,801.0,481.0,422.0,842.0,21.0,23.00