In [3]:
import pandas as pd
import numpy as np
import pickle

In [4]:
df = pd.read_csv(r'C:\Users\Cameron\OneDrive\Documents\DCU_Data\MWBW full dataset 2377 participants_anonymised (1).csv')

data_frame = df[['gender','age','run_c1_t1','run_c2_t1','run_c3_t1','run_c4_t1','run_c1_t2','run_c2_t2','run_c3_t2','run_c4_t2',
                 'skip_c1_t1', 'skip_c2_t1','skip_c3_t1','skip_c1_t2','skip_c2_t2','skip_c3_t2','gallop_c1_t1','gallop_c2_t1',
                 'gallop_c3_t1','gallop_c3_t1','gallop_c4_t1','gallop_c1_t2','gallop_c2_t2','gallop_c3_t2','gallop_c4_t2',
                 'slide_c1_t1','slide_c2_t1','slide_c3_t1','slide_c4_t1','slide_c1_t2','slide_c2_t2','slide_c3_t2','slide_c4_t2',
                 'hop_c1_t1','hop_c2_t1','hop_c3_t1','hop_c4_t1','hop_c5_t1','hop_c1_t2','hop_c2_t2','hop_c3_t2','hop_c4_t2', 
                 'hop_c5_t2','hj_c1_t1','hj_c2_t1','hj_c3_t1','hj_c4_t1','hj_c1_t2','hj_c2_t2','hj_c3_t2','hj_c4_t2','vj_c1_t1',
                 'vj_c2_t1','vj_c3_t1','vj_c4_t1','vj_c5_t1','vj_c6_t1','vj_c1_t2','vj_c2_t2','vj_c3_t2','vj_c4_t2','vj_c5_t2', 
                 'vj_c6_t2','catch_c1_t1','catch_c2_t1','catch_c3_t1','catch_c1_t2','catch_c2_t2','catch_c3_t2','throw_c1_t1', 
                 'throw_c2_t1','throw_c3_t1','throw_c4_t1','throw_c1_t2','throw_c2_t2','throw_c3_t2','throw_c4_t2','roll_c1_t1',
                 'roll_c2_t1','roll_c3_t1','roll_c4_t1','roll_c1_t2','roll_c2_t2','roll_c3_t2','roll_c4_t2','kick_c1_t1', 
                 'kick_c2_t1','kick_c3_t1','kick_c4_t1','kick_c1_t2','kick_c2_t2','kick_c3_t2','kick_c4_t2','2hs_c1_t1', 
                 '2hs_c2_t1','2hs_c3_t1','2hs_c4_t1','2hs_c5_t1','2hs_c1_t2','2hs_c2_t2','2hs_c3_t2','2hs_c4_t2','2hs_c5_t2', 
                 '1hs_c1_t1','1hs_c2_t1','1hs_c3_t1','1hs_c4_t1','1hs_c1_t2','1hs_c2_t2','1hs_c3_t2','1hs_c4_t2','bounce_c1_t1',
                 'bounce_c2_t1','bounce_c3_t1','bounce_c1_t2','bounce_c2_t2','bounce_c3_t2']].copy()

data_frame = data_frame.dropna()
data_frame = data_frame.reset_index(drop=True)
data_frame = data_frame.astype('float')

data_frame

,gender,age,run_c1_t1,run_c2_t1,run_c3_t1,run_c4_t1,run_c1_t2,run_c2_t2,run_c3_t2,run_c4_t2,...,1hs_c1_t2,1hs_c2_t2,1hs_c3_t2,1hs_c4_t2,bounce_c1_t1,bounce_c2_t1,bounce_c3_t1,bounce_c1_t2,bounce_c2_t2,bounce_c3_t2
0,2.0,6.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,...,0.0,0.0,0.0,0.0,1.0,1.0,0.0,1.0,1.0,0.0
1,1.0,6.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,...,1.0,1.0,1.0,1.0,0.0,1.0,0.0,0.0,1.0,0.0
2,1.0,6.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,...,1.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0
3,2.0,5.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,...,1.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0
4,1.0,6.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1988,2.0,11.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,...,1.0,1.0,1.0,0.0,1.0,1.0,1.0,1.0,1.0,1.0
1989,2.0,11.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,...,0.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0
1990,2.0,11.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,...,0.0,1.0,1.0,0.0,1.0,1.0,1.0,1.0,1.0,1.0
1991,2.0,11.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,...,1.0,0.0,1.0,0.0,1.0,1.0,1.0,0.0,1.0,1.0
1992,2.0,11.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,...,0.0,0.0,1.0,0.0,1.0,1.0,1.0,1.0,1.0,1.0

In [5]:
entire_dataset = data_frame.copy()
entire_dataset.drop(['age','gender'], inplace=True, axis=1)

entire_dataset

,run_c1_t1,run_c2_t1,run_c3_t1,run_c4_t1,run_c1_t2,run_c2_t2,run_c3_t2,run_c4_t2,skip_c1_t1,skip_c2_t1,...,1hs_c1_t2,1hs_c2_t2,1hs_c3_t2,1hs_c4_t2,bounce_c1_t1,bounce_c2_t1,bounce_c3_t1,bounce_c1_t2,bounce_c2_t2,bounce_c3_t2
0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,0.0,...,0.0,0.0,0.0,0.0,1.0,1.0,0.0,1.0,1.0,0.0
1,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,0.0,0.0,...,1.0,1.0,1.0,1.0,0.0,1.0,0.0,0.0,1.0,0.0
2,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,0.0,1.0,...,1.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0
3,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,0.0,0.0,...,1.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0
4,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1988,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,0.0,...,1.0,1.0,1.0,0.0,1.0,1.0,1.0,1.0,1.0,1.0
1989,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,0.0,...,0.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0
1990,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,0.0,...,0.0,1.0,1.0,0.0,1.0,1.0,1.0,1.0,1.0,1.0
1991,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,...,1.0,0.0,1.0,0.0,1.0,1.0,1.0,0.0,1.0,1.0
1992,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,...,0.0,0.0,1.0,0.0,1.0,1.0,1.0,1.0,1.0,1.0

In [6]:
entire_matrix = entire_dataset.corr()

#entire_matrix.to_csv('entire_matrix.csv')

#entire_matrix.to_pickle('entire_matrix.pickle')

entire_matrix

,run_c1_t1,run_c2_t1,run_c3_t1,run_c4_t1,run_c1_t2,run_c2_t2,run_c3_t2,run_c4_t2,skip_c1_t1,skip_c2_t1,...,1hs_c1_t2,1hs_c2_t2,1hs_c3_t2,1hs_c4_t2,bounce_c1_t1,bounce_c2_t1,bounce_c3_t1,bounce_c1_t2,bounce_c2_t2,bounce_c3_t2
run_c1_t1,1.000000,0.459338,0.274330,0.398315,0.823802,0.445484,0.296307,0.409946,0.112430,0.105735,...,0.044751,0.121002,0.077621,0.047433,0.109513,0.101658,0.077134,0.102428,0.100950,0.077617
run_c2_t1,0.459338,1.000000,0.385461,0.539540,0.452411,0.944176,0.400750,0.551233,0.168332,0.066431,...,0.057124,0.071711,0.058916,0.044278,0.179144,0.109398,0.121466,0.127255,0.131550,0.101648
run_c3_t1,0.274330,0.385461,1.000000,0.396794,0.255486,0.379387,0.911436,0.405324,0.112265,0.070062,...,0.116244,0.104719,0.096972,0.104647,0.097171,0.075586,0.086998,0.046146,0.110021,0.058271
run_c4_t1,0.398315,0.539540,0.396794,1.000000,0.402992,0.524464,0.404141,0.917458,0.173713,0.081531,...,0.043724,0.080346,0.054050,0.036831,0.121293,0.108190,0.107867,0.088994,0.126575,0.094731
run_c1_t2,0.823802,0.452411,0.255486,0.402992,1.000000,0.452411,0.277202,0.428957,0.140084,0.114563,...,0.059466,0.121002,0.068399,0.059240,0.116606,0.101658,0.096165,0.079645,0.110698,0.080684
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
bounce_c2_t1,0.101658,0.109398,0.075586,0.108190,0.101658,0.109398,0.086638,0.089239,0.180797,0.122895,...,0.037097,0.195218,0.154193,0.039306,0.273748,1.000000,0.320571,0.472755,0.612951,0.471554
bounce_c3_t1,0.077134,0.121466,0.086998,0.107867,0.096165,0.121466,0.102433,0.111342,0.269257,0.167787,...,0.189128,0.227163,0.275952,0.178746,0.530664,0.320571,1.000000,0.301758,0.462138,0.562456
bounce_c1_t2,0.102428,0.127255,0.046146,0.088994,0.079645,0.132501,0.054596,0.080640,0.212776,0.121321,...,0.017497,0.129691,0.177606,0.022785,0.562356,0.472755,0.301758,1.000000,0.243241,0.586077
bounce_c2_t2,0.100950,0.131550,0.110021,0.126575,0.110698,0.126312,0.122292,0.122487,0.207968,0.146506,...,0.123390,0.194915,0.186491,0.112804,0.460485,0.612951,0.462138,0.243241,1.000000,0.313632
bounce_c3_t2,0.077617,0.101648,0.058271,0.094731,0.080684,0.091760,0.058057,0.099146,0.238556,0.136339,...,0.110165,0.221210,0.277051,0.118192,0.410494,0.471554,0.562456,0.586077,0.313632,1.000000

In [5]:
male_dataset = data_frame[(data_frame['gender'] == 1)].copy()

male_dataset.drop(['age','gender'], inplace=True, axis=1)

In [6]:
male_matrix = male_dataset.corr()

male_matrix.to_csv('male_matrix.csv')

male_matrix.to_pickle('male_matrix.pickle')

In [7]:
female_dataset = data_frame[(data_frame['gender'] == 2)].copy()

female_dataset.drop(['age','gender'], inplace=True, axis=1)

In [8]:
female_matrix = female_dataset.corr()

female_matrix.to_csv('female_matrix.csv')

female_matrix.to_pickle('female_matrix.pickle')

In [9]:
age5_dataset = data_frame[(data_frame['age'] == 5)].copy()

In [10]:
age6_dataset = data_frame[(data_frame['age'] == 6)].copy()

In [11]:
age7_dataset = data_frame[(data_frame['age'] == 7)].copy()

In [12]:
age8_dataset = data_frame[(data_frame['age'] == 8)].copy()

In [13]:
age9_dataset = data_frame[(data_frame['age'] == 9)].copy()

In [14]:
age10_dataset = data_frame[(data_frame['age'] == 10)].copy()

In [15]:
age11_dataset = data_frame[(data_frame['age'] == 11)].copy()

In [16]:
age12_dataset = data_frame[(data_frame['age'] == 12)].copy()

In [17]:
age13_dataset = data_frame[(data_frame['age'] == 13)].copy()

In [18]:
age14_dataset = data_frame[(data_frame['age'] == 14)].copy()

In [19]:
age5_male = age5_dataset[(age5_dataset['gender'] == 1)].copy()

age5_male.drop(['age','gender'], inplace=True, axis=1)

In [20]:
age5_male_matrix = age5_male.corr()

age5_male_matrix.to_csv('age5_male_matrix.csv')

age5_male_matrix.to_pickle('age5_male_matrix.pickle')

In [21]:
age5_female = age5_dataset[(age5_dataset['gender'] == 2)].copy()

age5_female.drop(['age','gender'], inplace=True, axis=1)
age5_dataset.drop(['age','gender'], inplace=True, axis=1)

In [22]:
age5_female_matrix = age5_female.corr()

age5_female_matrix.to_csv('age5_female_matrix.csv')

age5_female_matrix.to_pickle('age5_female_matrix.pickle')

In [23]:
age5_matrix = age5_dataset.corr()

age5_matrix.to_csv('age5_matrix.csv')

age5_matrix.to_pickle('age5_matrix.pickle')

In [24]:
age6_male = age6_dataset[(age6_dataset['gender'] == 1)].copy()

age6_male.drop(['age','gender'], inplace=True, axis=1)

In [25]:
age6_male_matrix = age6_male.corr()

age6_male_matrix.to_csv('age6_male_matrix.csv')

age6_male_matrix.to_pickle('age6_male_matrix.pickle')

In [26]:
age6_female = age6_dataset[(age6_dataset['gender'] == 2)].copy()

age6_female.drop(['age','gender'], inplace=True, axis=1)
age6_dataset.drop(['age','gender'], inplace=True, axis=1)

In [27]:
age6_female_matrix = age6_female.corr()

age6_female_matrix.to_csv('age6_female_matrix.csv')

age6_female_matrix.to_pickle('age6_female_matrix.pickle')

In [28]:
age6_matrix = age6_dataset.corr()

age6_matrix.to_csv('age6_matrix.csv')

age6_matrix.to_pickle('age6_matrix.pickle')

In [29]:
age7_male = age7_dataset[(age7_dataset['gender'] == 1)].copy()

age7_male.drop(['age','gender'], inplace=True, axis=1)

In [30]:
age7_male_matrix = age7_male.corr()

age7_male_matrix.to_csv('age7_male_matrix.csv')

age7_male_matrix.to_pickle('age7_male_matrix.pickle')

In [31]:
age7_female = age7_dataset[(age7_dataset['gender'] == 2)].copy()

age7_female.drop(['age','gender'], inplace=True, axis=1)
age7_dataset.drop(['age','gender'], inplace=True, axis=1)

In [32]:
age7_female_matrix = age7_female.corr()

age7_female_matrix.to_csv('age7_female_matrix.csv')

age7_female_matrix.to_pickle('age7_female_matrix.pickle')

In [33]:
age7_matrix = age7_dataset.corr()

age7_matrix.to_csv('age7_matrix.csv')

age7_matrix.to_pickle('age7_matrix.pickle')

In [34]:
age8_male = age8_dataset[(age8_dataset['gender'] == 1)].copy()

age8_male.drop(['age','gender'], inplace=True, axis=1)

In [35]:
age8_male_matrix = age8_male.corr()

age8_male_matrix.to_csv('age8_male_matrix.csv')

age8_male_matrix.to_pickle('age8_male_matrix.pickle')

In [36]:
age8_female = age8_dataset[(age8_dataset['gender'] == 2)].copy()

age8_female.drop(['age','gender'], inplace=True, axis=1)
age8_dataset.drop(['age','gender'], inplace=True, axis=1)

In [37]:
age8_female_matrix = age8_female.corr()

age8_female_matrix.to_csv('age8_female_matrix.csv')

age8_female_matrix.to_pickle('age8_female_matrix.pickle')

In [38]:
age8_matrix = age8_dataset.corr()

age8_matrix.to_csv('age8_matrix.csv')

age8_matrix.to_pickle('age8_matrix.pickle')

In [39]:
age9_male = age9_dataset[(age9_dataset['gender'] == 1)].copy()

age9_male.drop(['age','gender'], inplace=True, axis=1)

In [40]:
age9_male_matrix = age9_male.corr()

age9_male_matrix.to_csv('age9_male_matrix.csv')

age9_male_matrix.to_pickle('age9_male_matrix.pickle')

In [41]:
age9_female = age9_dataset[(age9_dataset['gender'] == 2)].copy()

age9_female.drop(['age','gender'], inplace=True, axis=1)
age9_dataset.drop(['age','gender'], inplace=True, axis=1)

In [42]:
age9_female_matrix = age9_female.corr()

age9_female_matrix.to_csv('age9_female_matrix.csv')

age9_female_matrix.to_pickle('age9_female_matrix.pickle')

In [43]:
age9_matrix = age9_dataset.corr()

age9_matrix.to_csv('age9_matrix.csv')

age9_matrix.to_pickle('age9_matrix.pickle')

In [44]:
age10_male = age10_dataset[(age10_dataset['gender'] == 1)].copy()

age10_male.drop(['age','gender'], inplace=True, axis=1)

In [45]:
age10_male_matrix = age10_male.corr()

age10_male_matrix.to_csv('age10_male_matrix.csv')

age10_male_matrix.to_pickle('age10_male_matrix.pickle')

In [46]:
age10_female = age10_dataset[(age10_dataset['gender'] == 2)].copy()

age10_female.drop(['age','gender'], inplace=True, axis=1)
age10_dataset.drop(['age','gender'], inplace=True, axis=1)

In [47]:
age10_female_matrix = age10_female.corr()

age10_female_matrix.to_csv('age10_female_matrix.csv')

age10_female_matrix.to_pickle('age10_female_matrix.pickle')

In [48]:
age10_matrix = age10_dataset.corr()

age10_matrix.to_csv('age10_matrix.csv')

age10_matrix.to_pickle('age10_matrix.pickle')

In [49]:
age11_male = age11_dataset[(age11_dataset['gender'] == 1)].copy()

age11_male.drop(['age','gender'], inplace=True, axis=1)

In [50]:
age11_male_matrix = age11_male.corr()

age11_male_matrix.to_csv('age11_male_matrix.csv')

age11_male_matrix.to_pickle('age11_male_matrix.pickle')

In [51]:
age11_female = age11_dataset[(age11_dataset['gender'] == 2)].copy()

age11_female.drop(['age','gender'], inplace=True, axis=1)
age11_dataset.drop(['age','gender'], inplace=True, axis=1)

In [52]:
age11_female_matrix = age11_female.corr()

age11_female_matrix.to_csv('age11_female_matrix.csv')

age11_female_matrix.to_pickle('age11_female_matrix.pickle')

In [53]:
age11_matrix = age11_dataset.corr()

age11_matrix.to_csv('age11_matrix.csv')

age11_matrix.to_pickle('age11_matrix.pickle')

In [54]:
age12_male = age12_dataset[(age12_dataset['gender'] == 1)].copy()

age12_male.drop(['age','gender'], inplace=True, axis=1)

In [55]:
age12_male_matrix = age12_male.corr()

age12_male_matrix.to_csv('age12_male_matrix.csv')

age12_male_matrix.to_pickle('age12_male_matrix.pickle')

In [56]:
age12_female = age12_dataset[(age12_dataset['gender'] == 2)].copy()

age12_female.drop(['age','gender'], inplace=True, axis=1)
age12_dataset.drop(['age','gender'], inplace=True, axis=1)

In [57]:
age12_female_matrix = age12_female.corr()

age12_female_matrix.to_csv('age12_female_matrix.csv')

age12_female_matrix.to_pickle('age12_female_matrix.pickle')

In [58]:
age12_matrix = age12_dataset.corr()

age12_matrix.to_csv('age12_matrix.csv')

age12_matrix.to_pickle('age12_matrix.pickle')

In [59]:
age13_male = age13_dataset[(age13_dataset['gender'] == 1)].copy()

age13_male.drop(['age','gender'], inplace=True, axis=1)

In [60]:
age13_male_matrix = age13_male.corr()

age13_male_matrix.to_csv('age13_male_matrix.csv')

age13_male_matrix.to_pickle('age13_male_matrix.pickle')

In [61]:
age13_female = age13_dataset[(age13_dataset['gender'] == 2)].copy()

age13_female.drop(['age','gender'], inplace=True, axis=1)
age13_dataset.drop(['age','gender'], inplace=True, axis=1)

In [62]:
age13_female_matrix = age13_female.corr()

age13_female_matrix.to_csv('age13_female_matrix.csv')

age13_female_matrix.to_pickle('age13_female_matrix.pickle')

In [63]:
age13_matrix = age13_dataset.corr()

age13_matrix.to_csv('age13_matrix.csv')

age13_matrix.to_pickle('age13_matrix.pickle')

In [64]:
age14_male = age14_dataset[(age14_dataset['gender'] == 1)].copy()

age14_male.drop(['age','gender'], inplace=True, axis=1)

In [65]:
age14_male_matrix = age14_male.corr()

age14_male_matrix.to_csv('age14_male_matrix.csv')

age14_male_matrix.to_pickle('age14_male_matrix.pickle')

In [66]:
age14_female = age14_dataset[(age14_dataset['gender'] == 2)].copy()

age14_female.drop(['age','gender'], inplace=True, axis=1)
age14_dataset.drop(['age','gender'], inplace=True, axis=1)

In [67]:
age14_female_matrix = age14_female.corr()

age14_female_matrix.to_csv('age14_female_matrix.csv')

age14_female_matrix.to_pickle('age14_female_matrix.pickle')

In [68]:
age14_matrix = age14_dataset.corr()

age14_matrix.to_csv('age14_matrix.csv')

age14_matrix.to_pickle('age14_matrix.pickle')